Club Brugge K.V.

club brugge
years
club brugge koninklijke voetbalvereniging
flemish pronunciation
english referred bruges football club bruges belgium
founded top clubs belgium
home ground jan breydel stadium
capacity
club brugge major rival
anderlecht
shares jan breydel stadium city rival cercle brugge
contest bruges derby
long history
club brugge enjoyed european football success
reaching european finals european semi finals
club brugge belgian club played final european cup
forerunner current uefa champions league
beaten liverpool
final season
lost uefa cup final liverpool
club brugge holds record number consecutive participations uefa cup
club created students catholic school broeders xaverianen neutral school koninklijk atheneum
club recreated
adopted official date foundation
official board installed club
club created members brugsche
club created city
financial difficult brugeois year leave ubssa
brugeois joined brugsche continued football club brugeois
vlaamsche joined brugeois
moved stadium named
klokke
brugeois reached belgian cup final lost union
club time champions division
club number matricule number year royal title
low club relegated division
president albert dyserynck changed club statute profit association
president albert dyserynck suddenly died honoured changing stadium albert dyserynckstadion
rfc brugeois promoted division relegated future
won belgian cup time beerschot
penalty
club changed flemisch club brugge
moved albert dyserynckstadion olympiastadion
current jan breydelstadion
austrian coach ernst happel
club brugge reached finals uefa cup lost liverpool
ernst happel
club faced liverpool european final
time european champions clubs cup final
lost
club brugge belgian club reached finals european biggest competition
daniel amokachi goal scorer champions league
scored cska moskva
olympiastadion expand euro organisation
changed jan breydelstadion
belgian club create channel
appearances
games played
won
drawn
lost
goals
goals
total points uefa coefficient
quarter finals upwards
finals
european cup
uefa champions league
uefa cup winners cup
uefa cup
uefa europa league
november
source
uefa
website
january
note
flags national team defined fifa eligibility rules
players hold fifa nationality
recent transfers
list belgian football transfers summer
note
flags national team defined fifa eligibility rules
players hold fifa nationality
july
note
flags national team defined fifa eligibility rules
players hold fifa nationality
note
flags national team defined fifa eligibility rules
players hold fifa nationality
man
reserved club supporters
image
commons
thumb
flag belgium
civil
svg
flag belgium
civil
svg
png sterchele
striker
posthumous
sterchele died single person car accident
