Portal:House, M.D.

house
house
american medical drama
debuted fox network november
show created david shore executive produced shore film director bryan singer
united states television season
series watched scripted program watched program
american idol dancing stars
house stars english actor hugh laurie american title character
gregory house
maverick medical genius heads team diagnosticians fictional princeton plainsboro teaching hospital
original diagnostic team consists
robert chase
jesse spencer
allison cameron
jennifer morrison
eric foreman
omar epps
fourth season
team disbanded house gradually winnows field forty applicants team consisting
thirteen
olivia wilde
chris taub
peter jacobson
lawrence kutner
kal penn
main characters
lisa cuddy
lisa edelstein
dean medicine hospital administrator princeton plainsboro teaching hospital
james wilson
robert sean leonard
head department oncology house friend
house gained awards nominations
hugh laurie received golden globe award actor television drama screen actors guild award outstanding performance male actor drama series
house received peabody award peabody board called
unorthodox lead character misanthropic diagnostician
cases fit medical sherlock holmes
helped make house
distinctive doctor drama decade
show gained consecutive primetime emmy award nominations outstanding drama series
house ended eighth seasons broadcasting
house
allison cameron
fictional character fox medical drama house
portrayed jennifer morrison
immunologist
cameron member
gregory house team handpicked specialists princeton plainsboro teaching hospital department diagnostic medicine
hired months prior pilot episode
house explicitly informed hired based believed pretty girl medicine shows greater dedication compared ordinary student easily easier job
cameron honesty
sincerity
idealism strong ethical center
hyperopic atheist
cameron objects house reliance deceiving patients head head times issue
reluctant deliver bad news patients families
characters gregory house lisa cuddy james wilson allison cameron robert chase eric foreman remy
thirteen
hadley chris taub lawrence kutner michael tritter paul attanasio katie jacobs david shore bryan singer hugh laurie lisa edelstein omar epps robert sean leonard jennifer morrison jesse spencer peter jacobson kal penn olivia wilde episodes awards nominations soundtrack
pilot
episode television series house
episode premiered fox network november
introduces character
gregory house
played hugh laurie
maverick antisocial team diagnosticians fictional princeton plainsboro teaching hospital jersey
episode features
house attempts diagnose grade school teacher collapses class
house created david shore
idea curmudgeonly title character doctor visit
initially
producer bryan singer wanted american play house
british actor hugh laurie audition convinced foreign actor play role
shore wrote house character parallels sherlock holmes
show producers wanted house handicapped
gave character damaged leg arising improper diagnosis
episode received generally positive reviews
character house widely noted unique aspect episode series
reviewers sherwin nuland slate believed cruel character tolerated real life
initial broadcast
pilot
watched approximately million viewers
making sixty watched show week
back entrance frist campus center princeton university
exterior shots princeton plainsboro teaching hospital shot
commons
purge server cache
sean leonard
index house
quotes
php
html
portal
house
quotes
page exist
house
quotes
portal
house
quotes
