R.E.M.

american rock band athens
georgia
formed singer michael stipe
guitarist peter buck
bassist mike mills
drummer bill berry
popular alternative rock bands
gained early attention due buck ringing
arpeggiated guitar style stipe unclear vocals
released single
radio free europe
independent record label hib tone
single chronic town
band release
records
group released critically acclaimed debut album
murmur
built reputation years subsequent releases
constant touring
support college radio
years underground success
achieved mainstream hit single
love
group signed warner bros
records
began espouse political environmental concerns playing large arenas worldwide
early
alternative rock began experience broad mainstream success
viewed subsequent acts nirvana pavement pioneer genre released commercially successful albums
time
automatic people
veered band established sound
release
monster
return rock oriented sound
band began tour years support album
tour marred medical emergencies suffered band members
signed warner bros
reported
time expensive recording contract history
year
bill berry left band
buck
mills
stipe continued group trio
musical style
band continued career decade mixed critical commercial success
band inducted rock roll hall fame
disbanded september
announcing split website
january
michael stipe met peter buck athens record store buck worked
pair discovered shared similar tastes music
punk rock protopunk artists patti smith
television
velvet underground
stipe
turns buying records buck saving
stipe buck met fellow university georgia students mike mills bill berry
played music high school
quartet agreed collaborate songs
stipe commented
grand plan
unnamed band spent months rehearsing played show april
friend birthday party held converted episcopal church athens
names
twisted kites
cans piss
negro wives
band settled
stipe selected random dictionary
band members eventually dropped school focus developing group
found manager jefferson holt
record store clerk impressed
performance hometown chapel hill
north carolina
moved athens
success athens surrounding areas
band drew progressively larger crowds shows
caused resentment athens music scene
year half
toured southern united states
touring arduous touring circuit alternative rock bands exist
group tour blue van driven holt
band members lived food allowance day
summer
recorded single
radio free europe
producer mitch easter drive studios winston salem
north carolina
single released local independent record label hib tone initial pressing thousand copies
quickly sold
limited pressing
single garnered critical acclaim
listed ten singles year york times
recorded chronic town mitch easter october
planned release indie label named dasht hopes
records acquired demo band recording session easter circulating months
band turned advances major label rca records favor
signed contract
released chronic town august american release
positive review nme praised songs auras mystery
concluded
ring true
great hear unforced cunning
paired
producer stephen hague record debut album
hague emphasis technical perfection left band unsatisfied
band members asked label record easter
agreed
tryout
session
allowing band return north carolina record song
pilgrimage
easter producing partner don dixon
hearing track
permitted group record album dixon easter
bad experience hague
band recorded album process negation
refusing incorporate rock music guitar solos popular synthesizers
order give music timeless feel
completed album
murmur
greeted critical acclaim release
rolling stone listing album record year
album reached number billboard album chart
recorded version
radio free europe
album lead single reached number billboard singles chart
acclaim awarded album
murmur sold copies
jay boberg felt expectations
made national television appearance late night david letterman october
group performed
unnamed song
piece
eventually titled
central rain
single band album
reckoning
recorded easter dixon
album met critical acclaim
nme mat snow wrote reckoning
confirms
beautifully exciting groups planet
reckoning peaked number album unusually high chart placing college rock band airplay poor distribution overseas resulted charting higher number britain
band album
fables reconstruction
demonstrated change direction
dixon easter
chose producer joe boyd
worked fairport convention nick drake
record album england
band members found sessions unexpectedly difficult
miserable due cold winter weather considered poor food
situation brought band verge break
gloominess surrounding sessions ended providing context album
lyrically
stipe began create storylines mode southern mythology
noting interview inspired
idea men sitting fire
passing
fables grandchildren
fables reconstruction highest selling record released
america point
album performed poorly europe critical reception mixed
critics dreary poorly recorded
previous records
singles fables reconstruction mainstream radio
frustrated band reluctance achieve mainstream success
fourth album
enlisted john mellencamp producer don gehman
result
lifes rich pageant
featured stipe vocals closer forefront music
interview chicago tribune
peter buck related
michael
confident
shows projection voice
album improved markedly sales fables reconstruction eventually peaked number billboard album chart
single
fall
picked support commercial radio
album band certified gold selling copies
american college radio remained
core support
band beginning chart hits mainstream rock formats
music encountered resistance top radio
success lifes rich pageant
issued dead letter office
compilation tracks recorded band album sessions
issued sides left unreleased altogether
shortly
compiled
music video catalog
wolves
lower
band video release
succumbs
don gehman unable produce
album
suggested group work scott litt
litt producer band albums
document
featured stipe openly political lyrics
occupation
exhuming mccarthy
reactions conservative political environment american president ronald reagan
jon pareles york times wrote review album
ocument confident defiant
move cult band status mass popularity
album decrees band terms
document
breakthrough album
single
love
charted top
canada
january
document group album sell million copies
light band breakthrough
december cover rolling stone declared
america rock roll band
frustrated records satisfactory overseas distribution
left
contract expired signed major label warner bros
records
labels offered money
ultimately signed warner bros
amount million company assurance total creative freedom
aftermath group departure
released
compilation eponymous
assembled input band members
capitalize assets company possessed
band warner bros
debut
green
recorded nashville
tennessee
showcased group experimenting sound
record tracks ranged upbeat single
stand
hit united states
political material
rock oriented
orange crush
world leader pretend
address vietnam war cold war
green sell million copies worldwide
band supported album biggest visually developed tour date
featuring back projections art films playing stage
green tour
band members unofficially decided year
extended break band career
warner bros
issued music video compilation pop screen collect clips document green albums
months video album tourfilm featuring live performances filmed green world tour
reconvened mid record seventh album
time
departure green
band members wrote music traditional rock instrumentation including mandolin
organ
acoustic guitar adding overdubs creative process
released march
time band album top charts
record eventually sold
copies
million copies worldwide
album lead single
losing religion
worldwide hit received heavy rotation radio
music video mtv
losing religion
highest charting single
reaching number billboard charts
thereve life changing events career career gradual
mills years
talk life changing
losing religion closest
album single
shiny happy people
songs record feature vocals kate pierson fellow athens band
major hit
reaching number number
time garnered
nominations grammy awards
nominations artist year
band won awards
alternative music album
losing religion
short form music video pop performance duo group vocal
tour promote time
group played series shows
including appearance taped episode mtv unplugged released music videos song video album film
spending months
returned studio record album
late
band released automatic people
group intended make harder rocking album softer textures time
somber automatic people
move agonized crawl
melody maker
album dealt themes loss mourning inspired
sense
turning thirty
buck
songs featured string arrangements led zeppelin bassist john paul jones
considered number critics
buck mills
band album
automatic people reached numbers charts
generated american top hit singles
drive
man moon
hurts
album sell ten million copies worldwide
time
tour support album
decision forgo tour
conjunction stipe physical appearance
generated rumors singer dying hiv positive
vehemently denied band
band released slow paced albums row
album monster
buck
rock record
rock quotation marks
contrast sound predecessors
music monster consisted distorted guitar tones
minimal overdubs
touches glam rock
time
monster topped charts
record sold million copies worldwide
singles
frequency
kenneth
bang blame
band american top hits
singles monster reached top british charts
warner bros
assembled music videos album automatic people release parallel
january
set tour years
tour huge commercial success
period difficult group
march
berry collapsed stage performance lausanne
switzerland
suffered brain aneurysm
surgery immediately recovered fully month
berry aneurysm beginning series health problems plagued monster tour
mills undergo abdominal surgery remove intestinal adhesion july
month
stipe emergency surgery repair hernia
problems
group recorded bulk album road
band brought track recorders capture shows
recordings base elements album
final performances tour filmed released home video form road movie
signed warner bros
records reported
figure band constantly asserted originated media
rumored largest recording contract history point
group album adventures debuted number number
million copies album sold reversal group commercial fortunes previous years
time writer christopher john farley argued lesser sales album due declining commercial power alternative rock
year
parted ways manager jefferson holt
allegedly due sexual harassment charges levied member band home office athens
group lawyer
bertis downs
assumed managerial duties
april
band convened buck kauai vacation home record demos material intended album
band sought reinvent sound intended incorporate drum loops percussion experiments
sessions due begin october
berry decided
months contemplation discussions downs mills
rest band quitting
berry told band mates quit break result
stipe
mills
buck agreed carry piece blessing
berry publicly announced departure weeks october
berry told press
enthusiastic past anymore
job world
kind ready sit back reflect pop star anymore
stipe admitted band major contributor
mike
peter
guess legged dog dog
learn run differently
band canceled scheduled recording sessions result berry departure
bill
confusing
mills
rehearse drummer
remaining members
resumed work album february toast studios san francisco
band ended decade long collaboration scott litt hired pat mccarthy produce record
nigel godrich assistant producer
drafted screaming trees member barrett martin beck touring drummer joey waronker
recording process plagued tension
group close disbanding
bertis downs called emergency meeting band members sorted problems agreed continue group
led single
daysleeper
debuted top ten
album relative failure
selling copies mid eventually selling million copies worldwide
american sales declining
group commercial base shifting
records sold capita country band singles regularly entered top
year release
wrote instrumental score andy kaufman biographical film man moon
group
film title automatic people song
song
great
released single man moon soundtrack album
great
reached number american pop charts
band highest charting single
reaching number
recorded majority twelfth album reveal
canada ireland october
reveal shared
lugubrious pace
featured drumming joey waronker
contributions scott mccaughey
founder band minus buck
posies founder ken stringfellow
global sales album million
united states reveal sold number copies
album led single
imitation life
reached number
writing rock backpages
rev
friston album
loaded golden loveliness twist turn
comparison group
essentially unconvincing work adventures
similarly
rob sheffield rolling stone called reveal
spiritual renewal rooted musical
praised
ceaselessly astonishing beauty
warner bros
released compilation album dvd time
view
featured songs
bad day
animal
concert raleigh
north carolina
berry made surprise appearance
performing backing vocals
radio free europe
sat drum kit performance early
song
permanent vacation
marking performance band retirement
released sun
production album
stipe
album sounds taking couple records unchartered
territory
kind primitive howling
album release
mills
honestly
turned slower intended
terms speed songs
sun received mixed critical reception
peaked number billboard charts
single album
leaving york
top hit
record subsequent tour
band hired full time touring drummer
bill rieflin
previously member industrial music acts ministry pigface
video album perfect square released year
emi released compilation album covering
work tenure
called feel fine
years video album light mine
years label previously released compilations
singles collected
alternative recordings
month
original band members performed ceremony induction georgia music hall fame
rehearsing ceremony
band recorded cover john lennon
dream
instant karma
amnesty international campaign save darfur
tribute album benefiting amnesty international
single album bill berry studio recording band departure decade earlier
october
nominated induction rock roll hall fame year eligibility
band nominees accepted hall year
induction ceremony place march york waldorf astoria hotel
inducted pearl jam lead singer eddie songs bill berry
work group fourteenth album commenced early
band recorded producer jacknife lee vancouver dublin
played nights olympia theatre june july part
working rehearsal
live
band live album
featuring songs dublin show
released october
group live album live olympia
features performances residency
released accelerate early
album debuted number billboard charts
band eighth album top british album charts
rolling stone reviewer david fricke considered accelerate improvement band previous post berry albums
calling
records
made
released video album
live austin
concert recorded austin city limits
group recorded fifteenth album
collapse
jacknife lee locales including berlin
nashville
orleans
album
band aimed expansive sound intentionally short speedy approach implemented accelerate
album debuted number billboard
group tenth album reach top ten chart
release fulfilled
contractual obligations warner bros
band began recording material contract months intention releasing work
september
announced website
calling day band
stipe hoped fans realized
easy decision
things end
wanted
long time associate warner bros
senior vice president emerging technology ethan kaplan speculated shake ups record label influenced group decision disband
group discussed breaking years
encouraged continue lackluster critical commercial performance sun
mills
needed prove
fans critics
make great records
band members finished collaboration assembling compilation album part lies
part heart
part truth
part garbage
released november
album collect songs
warner bros
tenures
songs group final studio recordings post collapse sessions
november
mills stipe span promotional appearances british media
ruling option group reuniting
interview
peter buck typical
songs
minor key
mid tempo
enigmatic
semi folk rock balladish things
thinks degree
true
songwriting credited entire band
individual members responsible writing majority song
member equal vote songwriting process
buck conceded stipe
band lyricist
rarely persuaded follow idea favor
original line
divisions labor songwriting process
stipe write lyrics devise melodies
buck edge band musical directions
mills berry fine tune compositions due greater musical experience
michael stipe sings
biographer david buckley
wailing
keening
arching vocal figures
stipe harmonizes mills songs
chorus
stand
mills stipe alternate singing lyrics
creating dialogue
early articles band focused stipe singing style
mumbling
washington post
rendered lyrics indecipherable
creem writer john morthland wrote review murmur
idea songs
discern
lyrics
stipe commented
sing
control
pretty false
producer joe boyd convinced stipe begin singing recording fables reconstruction
stipe insisted early lyrics
nonsense
online chat
words
lot early stuff
remember
truth
stipe carefully crafted lyrics early
songs
stipe explained started writing lyrics
simple pictures
year grew tired approach
started experimenting lyrics make exact linear sense
mid
stipe pronunciation singing clearer
band decided lyrics convey ideas literal level
mills explained
made records written songs lyrically step question
michael confidence point
songs
cuyahoga
fall
lifes rich pageant dealt concerns pollution
stipe incorporated politically oriented concerns lyrics document green
political activism content songs reaction
surrounded
abject horror
stipe
active
stipe explored lyrical topics
automatic people dealt
mortality dying
pretty turgid stuff
stipe
monster critiqued love mass culture
peter buck style playing guitar singled distinctive aspect
music
buck
economical
arpeggiated
poetic
style reminded british music journalists american folk rock band byrds
buck stated
byrds guitarist roger mcguinn big influence guitar player
byrds influenced bands
including big star soft boys
inspired
comparisons made guitar playing johnny marr alternative rock contemporaries smiths
buck professed fan group
admitted initially criticized band simply tired fans influenced marr
band fact made debut
buck generally eschews guitar solos
explained
guitarists rip hot solo
people nuts
write songs suit
interested
mike mills melodic approach bass playing inspired paul mccartney beatles chris squire
mills
played melodic bass
piano bass ways
wanted play traditional locked kick drum
root note bass work
mills musical training band mates
made easier turn abstract musical ideas reality
pivotal creation development alternative rock genre
allmusic stated
mark point post punk turned alternative rock
early
musical style
stood contrast post punk wave genres preceded
music journalist simon reynolds noted post punk movement late early
swaths music menu
postpunk demystification pop schematics
felt liberating listen music rooted mystical awe blissed surrender
reynolds declared
band recalled music
plangent guitar chimes folk styled vocals
wistfully abstractly conjured visions frontiers america
important alt rock bands day
release murmur
impact musically commercially developing alternative genre early groups
leaving wake number jangle pop followers
early breakthrough success served inspiration alternative bands
spin referred
model
decisions
made set guidelines underground artists follow careers
spin charles aaron wrote
shown underground
punk inspired rock band industry whoring artistic integrity obvious
figured buy
sellout words
achieved american bohemian dream
steve wynn dream syndicate
invented ballgame bands follow sonic youth replacements nirvana butthole surfers
staked claim
musically
bands things
show big cool
biographer david buckley stated
period band sell estimated million albums
asserted rivals title biggest rock band world
career
band sold million records
alternative bands nirvana
pavement
live drawn inspiration
music
years richmond
virginia
important part life
pavement bob nastanovich
members band
pavement devoted song
unseen power picket fence
alternative compilation
discussing
albums length
kurt cobain nirvana vocal fan
plans collaborate musical project stipe death april
cobain told rolling stone interview earlier year
band
god
greatest
dealt success saints
delivering great music
career
members sought highlight social political issues
los angeles times
considered united states
liberal politically correct rock groups
band members
page
politically
sharing liberal progressive outlook
mills admitted occasionally dissension band members support
acknowledged
respect people disagree
discussions tend stay house
people divisions lie
people exploit purposes
buck noted stipe involved people ethical treatment animals
rest band
helped raise funds environmental
feminist human rights
involved campaigns encourage voter registration
green tour
stipe time sets inform audience variety pressing socio political issues
late
band
stipe
increasingly media coverage national television mention variety felt important
band attended mtv video music awards
stipe wore half dozen white shirts emblazoned slogans including
rainforest
love colors
handgun control
helped raise awareness aung san suu kyi human rights violations burma
worked freedom campaign campaign burma
stipe ran ads supporting democratic presidential candidate massachusetts governor michael dukakis vice president george
bush
band participated vote change tour sought mobilize american voters support democratic presidential candidate john kerry
political stance
coming wealthy rock band contract label owned multinational corporation
received criticism editor paul noyer
criticized band
celebrity liberalism
pain free form rebellion adopting
risk involved whatsoever
bit shoring customer loyalty
late
involved local politics hometown athens
georgia
buck explained sounds
michael local act lot stuff town make place
band donated funds local charities renovate preserve historic buildings town
political clout credited narrow election athens mayor gwen olooney
