T.I.

clifford joseph harris
born september
stage
nickname tip alter ego
american hip hop recording artist
record producer
actor
film producer
fashion designer published author bankhead
atlanta
georgia
embarked career childhood friends fellow rappers southern hip hop group pimp squad clique
founder chief executive officer
ceo
grand hustle records
released studio albums
trap muzik
urban legend
king
paper trail
mercy trouble man
heavy head
recent highly successful commercial market
released successful singles
bring
big shit poppin
swagga
featuring kanye west
jay lil wayne
live life
featuring rihanna
dead
featuring justin timberlake
plans release trouble man
wears crown
installment trouble man series
collaborative album grand hustle signee
tentatively titled man martian
served stints county jail
probation violations federal prison bid
federal weapons charge
serving months prison released seventh studio album
mercy
successful acting career
starring films takers atl
published author
written novels power beauty
trouble triumph
moderate success
born clifford joseph harris
september
atlanta
georgia
son late clifford
buddy
harris
violeta morgan
raised grandparents bankhead
atlanta
georgia
father lived york visit
father suffered alzheimer died disease
began rapping age
attended riverdale high school riverdale
georgia
attended douglass high school
dropped
teenager
drug dealer
rubber band man
reference custom wearing rubber bands wrist denote wealth terms drugs money
age
arrested times
nicknamed
tip
paternal great grandfather
kawan
prather
record executive
discovered signed
teenager
signing arista records subsidiary laface records
shortened
respect label mate tip
released debut album
october arista records
album spawned eponymous single
featured jamaican reggae entertainer beenie man
debut single
released june
single received airplay failed chart
album featured guest appearances pharrell williams neptunes
called
jay south
jazze pha
short
bone crusher
lil jon
pastor troy
youngbloodz southern hip hop group
album included production neptunes
toomp
madvac
grand hustle team
album guests appearances production team
album peaked number sold copies united states
critics pointed fact tracks sounded blatant rip offs
critics commented
claims king south
fails show prove
potential
talent matches confidence
headed stardom
due poor commercial reception album
dropped arista records
formed grand hustle entertainment started releasing mixtapes assistance drama
resurfaced summer fellow atlanta rapper label mate bone crusher song
scared
mixtapes mainstream exposure
scared
eventually recaptured major label attention signed joint venture deal atlantic records
released album trap muzik august
grand hustle records
debuted number sold copies week
spawned singles
easy
rubberband man
album featured guest appearances mjg
jazze pha
bun macboney produced jazze pha
kanye west
david banner
madvac toomp
march
warrant issued
arrest violated probation drug conviction
sentenced years prison
imprisoned cobb county
georgia
filmed unauthorized music video
month
allowed work release program
probation stemming conviction violating state controlled substances act giving false information
released probation
earned litany probation violations counties georgia offenses ranging possession firearm possession marijuana
appearing atlanta court
charges threatened man strip club year dropped lack evidence
arrested outstanding probation violation warrant florida
warrant claimed
complete required number community service hours sentenced battery female sheriff deputy university mall tampa
detained mall security guards time incident
wsb atlanta
attorney problem
technical matter
georgia florida
confusion arose
sentenced community service georgia driving suspended license
complete hours community service home state
rapper released bail shortly arrested
expected surrender florida state authorities week resolve matter
released studio album
urban legend
november
debuted number billboard
selling copies week
album lead single
bring
produced swizz beatz
released january top ten hit
peaking number billboard hot
single
peaked number twenty billboard hot
single
asap
reached number
charts
number
hip hop charts number rap chart
created video
asap
motivation
motivation
made number
hip hop singles chart
featured destiny child single
soldier
lil wayne
peaking number
hot
charts
received grammy award nominations song collaboration
soldier
destiny child lil wayne
rap solo performance
grammy awards
year won rap artist year
rap album year
rap album artist year
rap song artist year video clip artist year billboard music award male hip hop artist bet awards
fourth album
king
debuted number billboard chart half
selling copies week
released
front back
ride
promotional singles prior release album
singles garnered attention
album lead single
hit
helped promote album
atl
film
starred coincided album release
album spawned singles
wanna
live sky
remix
top back
included grand hustle compilation album grand hustle presents
streetz volume
king earned numerous awards nominations including grammy award nomination rap album
featured newly signed grand hustle artist young dro debut single
shoulder lean
reached top ten
hot
hot
hip hop songs hot rap tracks
won grammy award rap solo performance nominated rap song grammy awards
year
collaborated justin timberlake
love
proved worldwide hit
won grammy award rap
sung collaboration timberlake annual grammy awards won male hip hop artist bet awards straight time
served featured performer
takin
khaled featuring akon
fat joe
rick ross
birdman lil wayne
released album
july
lead single album
big shit poppin
produced mannie fresh released radio stations april
single
featuring wyclef jean
released june
sold copies united states
nielsen soundscan
debuted number billboard top
hip hop albums chart
chart topper row
king opened number billboard copies late march
album included guest performances jay
busta rhymes
wyclef jean
nelly
eminem
production eminem
jeff bass
mannie fresh
grand hustle
runners
blaze
wyclef jean danja
absent album production lineup
longtime producer toomp neptunes
october
released single
hurt
featuring busta rhymes alfamega
october
federal authorities arrested
hours bet hip hop awards atlanta
charged possession unregistered machine guns silencers
possession firearms convicted felon
arrest made parking lot downtown shopping center
witness identified walgreens drug store corner north piedmont avenues
arrested allegedly purchase guns
cooperating witness
bureau alcohol
tobacco
firearms explosives
federal officials
witness cooperating authorities days prior
arrest
cooperating witness arrested charges purchase guns federal agent
witness working
bodyguard july
authorities
walked atlanta united states district court appearing
magistrate judge alan
baverman october
judge alan
baverman required
post million bond
million cash million equity property owns
rapper required remain home medical appointments court appearances
people allowed live girlfriend children
visitors required approved court
suppression hearing scheduled february
performer pleaded guilty
federal weapons charges
sentenced undefined prison sentence
year house arrest hours community service
interview mtv serving prison time
stated
strategize comeback
sitting
time
collaborated mariah carey
lovin long time
remix
peaking number
hot number hot
hip hop songs
house arrest
began writing lyrics paper album
promotional single album
matter
released april
music video released june mtv premieres
promotional single
swing rag
featured vocals production swizz beatz
official lead single
released july
successful single career
breaking record highest jump number billboard hot
jumping number number
solo number chart
released sixth album
paper trail
september
title album refers lyrics written paper
rappers
abandoned style rapping debut album memorizing lyrics
representative explain
wanted
time put time
album debuted number billboard selling copies united states
single album
swagga
featuring kanye west
jay lil wayne
debuted peaked number billboard hot
single
live life
featuring rihanna
broke record billboard hot jumped number number
fourth single
dead
featuring justin timberlake
peaked number weeks billboard hot
eventually nominated grammy awards
rap
sung collaboration
rap song
grammy awards
nominated grammy awards
eventually winning rap performance duo group
swagga
remember
featuring mary
blige
released digitally july
planned single release
sixth studio album
paper trail
release eventually shelved
single peaked number billboard hot
october
hell life
released digitally peak number billboard hot
appeared episode kathy griffin
life list
episode
comedienne roscoe house chicken waffles gave lesson
swagger
november
testified murder trial member entourage close friend
philant johnson
murdered shooting occurred post concert party club
dedicated songs johnson
single version
live sky
recent hit
dead
johnson grave video
march
district judge charles
pannell
sentenced
year day prison ordered pay federal weapons charges
sentence reduced maximum years fine plea bargain
began serving sentence forrest city
arkansas
days prior imprisoned
performed farewell concert philips arena atlanta
georgia
released fcc forrest city december
moved halfway house atlanta
federal bureau prisons released ccm atlanta march
release prison
subjected audit finances
drug counseling
dna testing
random searches property
march
released halfway house
release studio working seventh studio album titled king uncaged
jim jonsin
producer previously worked single
singer trey songz
scheduled work project
made public appearance prison
stepping tameka
tiny
cottle support alzheimer research fundraiser
love fathers
atlanta opera venue
happy
joined cottle onstage end benefit
released promotional single titled
back
march
single peaked billboard hot charts
time
made featured guest appearance diddy dirty money single
good morning
single peaked charted internationally countries
made guest appearance larry king live
discuss larry king month prison term federal gun charges topics
released promotional soundtrack single entitled
yeah
takers
peaked number forty billboard hot number sixty canadian hot
released promotional single entitled
back
featured american singer keri hilson peaked number thirty
made featured single appearances jamie foxx single
winner
featuring justin timberlake drake single
fancy
featuring swizz beatz
singles made charted billboard charts peaking top
prior album release
decided release mixtape titled fuck mixtape
move controversial due title
feeling insulting mixtape format
addressed issue stating response people told focus album mixtape
defended decision release mixtape
songs
lot songs period pieces speak volumes
hold year year
dated
life direction
gonna put album make album platform present world
september
wife tiny arrested drug charges los angeles
arrest drug charges led
sentenced october
months prison violating terms probation
specifically possessing ecstasy
testing positive opiates associating convicted felon
october
drug charges
dropped
scrapped king uncaged title seventh studio album renamed mercy due prison sentencing
released lead single newly titled album
back
featuring chris brown
day sentenced back prison violating terms probation
back
peaked number seventy
november
reported back forrest city federal facility serve month sentence
date release set september
mercy released december
album peaked number sold copies week
riaa certified mercy gold copies sold
final single album
wrote
collaboration eminem
released december
peaking number eighteen
nominated grammy awards rap solo performance
back
grammy award rap performance duo group
fancy drake swizz beatz
grammy awards
nominated soul train music award hip hop song year
back
earned bet hip hop awards nominations hustler year
made award
club banger
good morning
april daughter born
early june
letter
releasing record future
couple weeks tops
hold til back action
june
song released
official website official youtube channel titled
yall
features fellow grand hustle rapper
hook
commenting song
letter
song release time
inspired write record differences suddenly incredibly evident short period time
originally atlantic records online store
song itunes vendors
spotify august peaked number seventy
august
released forrest city correctional facility arkansas
community living facility serve rest month prison sentence
released statement twitter
storm sun back
time shine shawty
beginning happy ending
inked deal reality show follow adjusts life free man incarceration announced working entitled
power beauty set released october
back federal custody september
hours release due dispute involving
taking luxury bus prison arkansas halfway house facility atlanta
attorney
steve sadow
told press federal bureau prisons moved
facility clarified dispute drug related
released prison back halfway house
released september
midnight
september
released
flexin
promotional single upcoming eighth studio album
song features vocals production big
reunited young jeezy
jeezy album
flexin
peaked number sixty billboard hot
peaked number sixty billboard hip hop
october
made appearances howard stern show view promote
power beauty
love story life streets discuss issues involving time prison
day
released promotional single
hear
featuring pharrell williams alias
release prison
appeared remixes including
spend
chainz
sleazy
niggas paris
jay kanye west
hard white
club
yelawolf featuring slaughterhouse
ima boss
meek mill alongside freestyle drake
headlines
lil wayne
featured southern rapper future single
magic
debut studio album pluto
song hopped release prison future
revealed title eighth studio album trouble man
title partly inspired marvin song
revealed billboard
previous interview rolling stone
debating titles
trouble man kill king
promotional single
pyro
released november
december
reality show
tiny
family hustle
premiered full episodes leaked internet
preparation album
released mixtape entitled
fuck city year day
songs mixtape charted billboard hot
hip hop songs
popped
featuring vocals production
dre
time night
featuring nelly
set
strange clouds
music video
mtv interviewed
confronted rumor
working collaborative album
responded
joint album
started joke
tip refer martian
lyrics
man martian
album title
kinda played
taking form organic
december
appeared york city hot radio station confirmed
working collaborative album titled man martian
march
announced signed iggy azalea
chipmunk trae tha truth grand hustle records
executive producer azalea debut extended play glory featured debut single
murda bizness
premiered march
march
released snippet
love life
trouble man promotional single
produced mars nothin
song officially released april
song peaked number
joined reggae singer
sean kingston single
back life
live
shot video track
sampled soul chart topping hit
back life
song peaked number fifty canada
visit angie martinez radio show
revealed album released september
recorded collaborations trey songz usher
dope
dope collabo
usher tip
atlanta natives
rico love told rap
time finally feel record gonna humongous hit
reality show
tiny
family hustle renewed season
airs september
released promotional song trouble man
entitled
appeared trey songz single album chapter titled
reasons
song peaked number forty
promotional single trouble man
entitled
released july
song peaked number seventy number eighty canada
september
appeared park promote book
trouble triumph
sequel previous
power beauty
visit
announced release date album set december
revealed album feature collaborations pharrell
cee green
kelly
lil wayne
rocky
stated working women clothing line
released song
trap back
premiered visit angie radio show
ball
released october
lead single upcoming eighth studio album
song featured fellow american rapper lil wayne produced american record producer rico love
alongside earl
song peaked number fifty number fifty canada
october
previewed twelve tracks album listening party york city
revealed titles
tracks previewed feature artists kendrick lamar
month
leaked illustrated cover art newly named album entitled
trouble man
heavy head track list newly added features album
explained
lot urban paper trail
apologetic mercy
diversified
lotta heart
lotta edge
creative album
harder shit coming
featuring andre released promotional single itunes november
peaked number hot
hip hop songs
featuring cee released itunes december sixth promotional single
shortly trouble man
heavy head released
announced release sequel album titled trouble man
wears crown
sequel due
recording material needed cited
songs
album debuted number billboard
week sales copies united states
january
sold copies
january
announced
drew close year contract atlantic records month
releasing trouble man
heavy head
reported proposed million deal label provide home imprint
tmz reported
drawn details
include
albums
percent publishing
touring
merchandise
film rights
corporate endorsement deals
exclusive signing grand hustle artists
allegedly coaxed biggest names industry
reports jay sign
hoping add roc nation
exclusive dinner katana
dre
thought proposed interscope signing rapper
met sony
offered million
spoke universal week
starred film
atl
loosely based rapper life growing atlanta attending skating rink named
jellybeans
skating rink changed due
jellybeans
giving movie rights
cast members included lauren london
antwan patton
evan ross
mykelti williamson
jason weaver
keith david
movie written tina gordon chism antwone fisher
produced timothy
bourne
tionne watkins
smith
directed christopher robinson
played character rashad swann
orphaned year senior high school
opening weekend
film grossed total
million
ranking united states box office
gross
million
appeared american gangster stevie lucas
drug kingpin frank lucas nephew
starred crime heist film takers
originally called bone deep
ghost
film directed john luessenhop produced william packer
michael ealy
tom lassally
jason geter
gary gilbert
film released august
grand hustle films rainforest films distributed screen gems
film includes chris brown
idris elba
matt dillon
paul walker
hayden christensen
zoe saldana
takers debuted number american box office
million opening weekend
executive producer
upcoming album produced artists mariah carey
cassidy
rick ross
maino
yung joc
young dro
executive produced soundtrack film hustle flow released collection record label
served executive producer iggy azalea debut album classic
songwriter ghostwriter
written diddy
dre
bun
keyshia cole bow wow
launched film company
grand hustle films
late
linked los angeles based production company entertainment executive produce reality show titled life mars chronicles life young prodigy music producer lamar
mars
edwards
partnered entertainment company grand hustle records produce slate television film projects
created reality show mtv called
road redemption
addition helping hurricane katrina relief efforts
worked troubled youths paulding detention center atlanta
provided scholarships single parent families boys girls clubs
headlined boost mobile rockcorps concert york radio city music hall
featured performers fat joe
slim thug
kanye west
held exclusively community service volunteers
part community service time
number middle grade high schools georgia
speaks students assembly holding positive message
maintaining philathropic view morals growing areas
june
lisa
left eye
lopes foundation
named deceased member multi platinum female group tlc
atlanta honored
lisa lopes award groundbreaking achievements music community service court ordered
steady list growing accomplishments
recognized
jay south
pharrell williams multi platinum production team neptunes
night club
club crucial
hosted giveaway bicycles neighborhood children boys girls club announcer greg street
asked opinion obama supporting gay marriage
responded people free
forbes magazine announced hip hop cash kings list early list top hip hop earning artists previous business year
listed list times
opened nightclub
club crucial bankhead
atlanta
considered popular clubs atlanta features full entertainment centers large flat screen tvs
pool rooms
vip rooms
food
celebrities monica
big boi
mike epps
shawty make appearances
club hosts weekly events monday night open mic night
free fridays
celebrity saturdays local hip hop artists perform songs club
chevrolet secured endorsement deal
earlier promote line cars
focus impala
due arrest federal gun charges
verge losing deal company
endorsement social networking website focusing hip hop culture named streetcred
website founded investment banker rocky williform
celebrities diddy
lil kim
jeezy accounts website
website temporarily shut notice
june
named global creative consultant martin cognac
xxl magazine revealed partnership include collaborative projects focus continuing philanthropic works
foundation
announced chelsea releasing signature brand liquor
lost endorsement deal axe body spray arrest drug possession
dispute ludacris started
disturbing tha peace rapper video
video
man wearing shirt
trap house
beaten
mistook logo refer
trap muzik
unit artist young buck asked fellow southern rappers
ludacris record track
stomp
recorded verse contained line young buck considered underhanded snub ludacris
gettin beat
ludicrous
young buck spoke ludacris verse
maintain neutrality controversy
ludacris recorded verse found album
record company wanted ludacris change verse sanctioned ludacris refused
replaced game album version
june
sunset tower hotel west hollywood
california
involved brawl
luncheon held kevin liles warner music group
parent company
label
atlantic records
fight ludacris manager chaka zulu
witnesses
punched zulu face choked melee ensued
brought home award hip hop artist bet awards
opportunity apologize scuffle disturbing tha peace executive chaka zulu earlier week
accepting award
expressed regret situation
fine line brilliance insanity
apparent reference troublesome alter ego
broadcast
cameras showed onetime rival ludacris smiling audience
audience stood applauded
rappers resolved dispute collaborated songs
ludacris sixth studio album
theater mind
top world
sixth studio album
paper trail
original version kanye west
allhiphop
lil flip altercation lil flip neighborhood
cloverland section houston
create dvd exposing lil flip fraud
cloverland entourage
met flip people
fight broke members lil flip entourage started swinging
bodyguards started shooting
day
houston
texas radio station talking altercation
revealed tape release upcoming mixtape
happen james prince stopped distributing tape
unknown
tape
feud squashed rap lot prince sit resolve feud
feud documented houston press
involved highly publicized feud shawty
feud characterized shawty track
dunn dunn
reply
haapnin
song
dunn dunn
appears question
roots bankhead
music video
haapnin
shot shawty housing project bowen homes
apparent insult shawty
interview
insisted song
matter
partially aimed shawty
feud reached climax november dirty awards entourages artists clashed ceremony
forcing shut
incidents forced police pepper spray evacuate audience
feud publicly squashed march
shawty
appeared stage club crucial bankhead
farewell concert
performance
gave interview mtv
stated feud shawty exaggerated media
beef
relationship xscape member tameka
tiny
cottle
couple married july
miami beach
florida
sons
clifford
king
joseph harris iii
born august
major philant harris
born
daughter lelah amore harris stillborn march
months complicated pregnancy
addition
sons girlfriend lashon dixon
messiah majesty
born
domani uriah
born
daughter named deyjah imani
born
relationship american singer
niko
marriage cottle
stepdaughter
zonnique pullins
born cottle zonnie zebo pullins
praised helping twenty year suicidal man atlanta named joshua starks
convincing man jumping story building
october
reportedly heard situation radio drove scene atlanta colony square building
drove site
asked police starks
talked man
convinced jump
stated
taking credit
couldve resolved
fact matter god put position
credit
